### PR TITLE
feat(cli): add alias flags for swa cli commands and options

### LINKED ISSUE #410: Introduce alias flags
**Is your feature request related to a problem? Please describe.**
The current flag names can be cumbersome and verbose to type each time. I'd like to suggest having shorter aliases.

**Describe the solution you'd like**

| swa flag| alias |
|-|-|
|--config|-c|
|--help|-h|
|--print-config|-g|
|--verbose|-v|

| swa start flag | alias |
|-|-|
|--app-location |-a|
|--api-location|-i|
|--api-port|-j|
|--devserver-timeout|-t|
|--func-args|-f|
|--host|-q|
|--open|-o|
|--port|-p|
|--run|-r|
|--ssl|-s|
|--ssl-cert|-e|
|--ssl-key|-k|
|--swa-config-location|-w|

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
Introduce alias flags for CLI config options specified by user. This PR resolves #410 

Alias flags and Unit tests added for:-
- [SWA CLI Global options](https://github.com/Azure/static-web-apps-cli/blob/ga/src/swa.d.ts#L125)
- [SWA CLI Start options](https://github.com/Azure/static-web-apps-cli/blob/ga/src/swa.d.ts#L140)
- [SWA CLI Deploy options](https://github.com/Azure/static-web-apps-cli/blob/ga/src/swa.d.ts#L171)
- [SWA CLI Init Options](https://github.com/Azure/static-web-apps-cli/blob/ga/src/swa.d.ts#L134)
- [SWA CLI Login Options](https://github.com/Azure/static-web-apps-cli/blob/ga/src/swa.d.ts#L194)
- [SWA CLI Build Options](https://github.com/Azure/static-web-apps-cli/blob/ga/src/swa.d.ts#L160)

### CODE REVIEW

**Comment by Devansu-Yadav** [comment]
@manekinekko Please review some of the tests that I have added in `https://github.com/Azure/static-web-apps-cli/tree/ga/src/core/utils/options.spec.ts` file as per your convenience so that I know if I'm doing it correctly or not 😅

**Review by manekinekko — APPROVED** [review]

**Comment by manekinekko** [comment]
You are in the right direction 👍

**Comment by Devansu-Yadav** [comment]
@manekinekko I have finished adding alias flags for all of the commands that have been created so far. Please review the alias flags for the command options and do let me know if they need to be updated. 

P.S:- I haven't added alias flags for a few short options like `--env`, `--auto` since I thought that they might not be needed as they are short (Do let me know, if needed, I can add them).

**Comment by Devansu-Yadav** [comment]
> @Devansu-Yadav thank you for taking the time to make those changes. Would you mind rebasing your PR on the `ga` branch one last time? The GA branch is ready, and ee are planning on merging this PR by tomorrow 😊

Sure, I'll make the changes! 👍

**Pull request merged**
