### PR TITLE
Reshmi/edit code owners

### PR DESCRIPTION
**Pull request by Reshmi-Sriram**
docs: update CODEOWNERS

### CODE REVIEW

**Review by manekinekko — APPROVED** [review]

**Comment by manekinekko** [comment]
@Reshmi-Sriram the Semantic Pull Request check is blocking. Can you add a prefix to your commit message as mentioned [here](https://github.com/Azure/static-web-apps-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines)?

**Comment by Reshmi-Sriram** [comment]
> @Reshmi-Sriram the Semantic Pull Request check is blocking. Can you add a prefix to your commit message as mentioned [here](https://github.com/Azure/static-web-apps-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines)?

Done!

**Comment by manekinekko** [comment]
@Reshmi-Sriram the commit message is still not valid. It should look something like `docs: update CODEOWNERS`

**Comment by Reshmi-Sriram** [comment]
> @Reshmi-Sriram the commit message is still not valid. It should look something like `docs: update CODEOWNERS`

Done. Hope this works :)

**Comment by manekinekko** [comment]
@Reshmi-Sriram I don't see any new commits on this branch?

**Comment by Reshmi-Sriram** [comment]
> @Reshmi-Sriram I don't see any new commits on this branch?

Ah my bad, just edited the comment instead of making a new commit. Now I did :)

**Pull request merged**
