### PR TITLE
Fixes issue-251

### PR DESCRIPTION
**Pull request by sgollapudi77**

### CODE REVIEW

**Comment by sgollapudi77** [comment]
@manekinekko can you review this if you get some free time. Thank you :D

**Comment by anthonychu** [comment]
Fixes #251

**Comment by manekinekko** [comment]
Hey @sgollapudi77 I will review this PR next week. I am ooo this week 😃

**Comment by manekinekko** [comment]
I tried to run this PR locally, but I am still getting the same error described in issue #251

Here are the steps I followed:
- `git checkout -b issue-251 origin/issue-251`
- `npm run build`
- `npm link .`
- follow steps in #251 to reproduce the bug

image

**Comment by sgollapudi77** [comment]
Hi @manekinekko, I forgot to make a change in SWA_CLI_API_URI(), but I have made that change and pushed it now. Can you try now. I'm able to use the custom name as my dev-server but the requests from the SWA are getting rejected with some ECONNRESET error.[
Screenshot (52)
](url)

**Pull request closed without merging**
