### PR TITLE
fix: File without extension return 404 #292

### PR DESCRIPTION
**Pull request by tush**
Fix for #292. @manekinekko : Can you validate please ?

### CODE REVIEW

**Comment by geromegrignon** [comment]
> Fix for #292. @manekinekko : Can you validate please ?

Hello @tush, all open source contributions are welcome (I'm not affiliated with Azure and this project).
But as the related issue was already assigned to someone else, you should consider there was probably another work in progress to address it. It's part of the contributing [guide](https://github.com/Azure/static-web-apps-cli/blob/main/CONTRIBUTING.md): `You don't want to duplicate effort.`

For such situations, I encourage you to collaborate with assigned people if you really want to work on it.

**Comment by santoshyadavdev** [comment]
> Fix for #292. @manekinekko : Can you validate please ?

Hey @tush I know you are excited as this is your first PR, and you might have ignored that this was already picked up, and assigned to me. Please as @geromegrignon mentioned please go through the issue before you pick up something next time. @manekinekko please assign this one to @tush

**Comment by tush** [comment]
Hello @santoshyadavdev, @geromegrignon ; I checked if any PR pending for this issue before creating one. But indeed missed the point you have mentioned. I understand it and will take care in future. Thank you guys 👍

**Comment by sgollapudi77** [comment]
Hey @tush we're merging this PR for now but as the related issue was already assigned to @santoshyadavdev, Kindly keep in mind the contributing [guide:](https://github.com/Azure/static-web-apps-cli/blob/main/CONTRIBUTING.md) `You don't want to duplicate effort`.

For such situations, we encourage you to collaborate with assigned people if you really want to work on it.

**Pull request merged**
