### PR TITLE
fix: update unzip package

### PR DESCRIPTION
**Pull request by cjk7989**
This PR replaces the unzip package with adm-zip and updates the code to avoid bug in node 18. The previous package unzipper was not compatible with node >= 18.16, which caused the bug "This version of xxx\Microsoft.DataApiBuilder.exe is not compatible with the version of Windows you're running" when using database connection. Refs: [#700](https://github.com/Azure/static-web-apps-cli/issues/700)

### CODE REVIEW

**Review by v1212 — APPROVED** [review]

**Comment by Cypher1** [comment]
Any chance this will be in an upcoming release? Looking forward to the fix landing :)

**Comment by cjk7989** [comment]
Yes, this will be in the next release.

If you want to apply this change now, here is an easy way to download and test it from GitHub:

- git clone https://github.com/Azure/static-web-apps-cli.git
- cd into the folder "static-web-apps-cli"
- run "npm install", then "npm run build"
- run "npm link ./", which allows you to use this version of swa-cli globally.
- * if you want to update the version of swa-cli, just delete this local folder "static-web-apps-cli" and run "npm install -g @azure/static-web-apps-cli" to reinstall the official version.

**Comment by cjk7989** [comment]
> Any chance this will be in an upcoming release? Looking forward to the fix landing :)

Yes, this will be in the next release.

If you want to apply this change now, here is an easy way to download and test it from GitHub:

- git clone https://github.com/Azure/static-web-apps-cli.git
- cd into the folder "static-web-apps-cli"
- run "npm install", then "npm run build"
- run "npm link ./", which allows you to use this version of swa-cli package globally.
- \* if you want to update the version of swa-cli, just delete this local folder "static-web-apps-cli" and run "npm install -g @azure/static-web-apps-cli" to reinstall the official version.

**Comment by thomasgauvin** [comment]
This release has just been published to npm! 🎉

**Pull request merged**
