### PR TITLE
feat: provide complete devcontainer with support for e2e tests

### LINKED ISSUE #425: Providing a complete DevContainer to run the tests
**Is your feature request related to a problem? Please describe.**
When you first start the DevContainer I noticed two things : 
- swa is not accessible on the path.
- Some tools are not installed in the DC when you want to test the code: dotnet, Azure Function Core..

**Describe the solution you'd like**
A complete DevContainer with all the tools and dependencies to run the following examples with the command swa start : 
- cypress/fixture/blazor-starter
- cypress/fixture/static

**Describe alternatives you've considered**
Running tests using **npm run e2e:start:static** and **npm run e2e:start:blazor** commands;
You have to install Dotnet package and azure function-core still.

**Additional context**

### PR DESCRIPTION
**Pull request by sinedied**
closes #425

### CODE REVIEW

**Comment by sinedied** [comment]
I tested static & blazor e2e tests in codespaces directly with it (BTW blazor e2e have failing tests regarding auth 😅 )

**Comment by manekinekko** [comment]
We need to update the Blazor app to match the static app. All e2e tests were written for the static app.

**Comment by aaronpowell** [comment]
Want me to look at the Blazor auth stuff?

**Comment by manekinekko** [comment]
@aaronpowell  that would be fantastic!

**Review by manekinekko — APPROVED** [review]

**Pull request merged**
