### PR TITLE
fix: Appended Query params to the URL

### LINKED ISSUE #312: Proxying request to remote dev server is missing query parameters
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

v0.7.2

**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running!

**Describe the bug**
It seems that when the CLI is proxying a request to a dev server that it is then missing the query parameters. For example a request to `http://localhost:4280/_next/image?url=%2Fvercel.svg&w=640&q=75`, looks to me as it end up as an request to `http://localhost:3000/_next/image` with no query parameters. 

**To Reproduce**
1. Clone (or replicate) the repository at https://github.com/jon-a-nygaard/bug-swa-cli-proxy
2. Open a terminal in the cloned repository and run `npm run dev`
3. Open http://localhost:3000/ to view expected result
4. Open a terminal in the cloned repository and run `npm run swa` (do not terminate previous terminal)
5. Open http://localhost:4280/ to view bug, open developer console to see error.

**Expected behavior**
I would like the proxy to perform a request to `http://localhost:3000/_next/image?url=%2Fvercel.svg&w=640&q=75`.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 93.0.4577.82 (Official Build) (64-bit)

**Additional context**

staticwebapp.config.json (simplified for this example):
```
{
  "routes": [],
  "responseOverrides": {}
}
```

Output from CLI when processing request:
```
--------------------------------------------------------
[swa] ------------------- processing route -------------------
[swa] --------------------------------------------------------
[swa] processing /_next/image?url=%2Fvercel.svg&w=640&q=75
[swa] checking for matching route
[swa] checking auth request
[swa]  - not an auth request
[swa] checking function request
[swa]  - not a function request
[swa] checking HTTP method: GET
[swa]  - method is valid (allow-list: GET,HEAD,OPTIONS)
[swa] checking for query params
[swa]  - query: url=%2Fvercel.svg&w=640&q=75
[swa] checking rewrite auth login request
[swa] checking rewrite auth logout request
[swa] checking authorizations for route
[swa]  - no matching rule
[swa]  - access authorized
[swa] using userConfig
[swa] - userConfig:
[swa]  - routes:
[swa]  - responseOverrides:
[swa]   - isLegacyConfigFile: false
[swa] checking storage content
[swa]  - query: url=%2Fvercel.svg&w=640&q=75
[swa] finding file for request
[swa]  - filePathFromRequest: /_next/image
[swa] checking mime types
[swa]  - extension: <empty>
[swa]  - found: application/octet-stream
[swa] constructing headers
[swa]  - matchingRouteHeaders: <undefined>
[swa]  - globalHeaders: <undefined>
[swa]  - url: /_next/image
[swa]  - target: http://localhost:3000
[swa] customUrl: false
[swa] is4xx: false
[swa] remote dev server detected. Proxying request
[swa]  - url: /_next/image
[swa]  - code: 200
[swa] GET http://localhost:3000/_next/image (proxy)
[swa] getting response from dev server
[swa] GET http://localhost:4280/_next/image - 400
```

### PR DESCRIPTION
**Pull request by sgollapudi77**
Fixes #312.

### CODE REVIEW

**Review by manekinekko — APPROVED** [review]

**Comment by manekinekko** [comment]
Thank you @sgollapudi77

**Comment by garand** [comment]
@manekinekko @sgollapudi77 I was running into this with setting up a Vite frontend with the SWA cli. Adding `matchingRewriteRouteQueryString` to the end results in this:

```
[swa] /src/logo.svgimport=
```

Notice the missing `?` prefix.

I instead replaced it with this:

```diff
if (doesMatchingRewriteRouteHaveQueryStringParameters) {
-    matchingRewriteRoutePath = sanitizedUrl.pathname + matchingRewriteRouteQueryString; // => /src/logo.svgimport=
+    matchingRewriteRoutePath = sanitizedUrl.pathname + sanitizedUrl.search;  // => /src/logo.svg?import
    core_1.logger.silly(` - query: ${chalk_1.default.yellow(matchingRewriteRouteQueryString)}`);
}
```

The mapping is now correct.

```
[swa] /src/logo.svg?import
```

And it correctly appends the search params and lets the Vite React starter load correctly.

I'll write up a separate PR for this.

**Comment by sgollapudi77** [comment]
@garand Thanks for noticing that. You're more than welcome to raise a PR and contribute :)

**Comment by garand** [comment]
@sgollapudi77 Created. https://github.com/Azure/static-web-apps-cli/pull/338

**Pull request merged**
